{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e45306f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 导入依赖\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import jieba\n",
    "import numpy as np\n",
    "import re\n",
    "from collections import Counter\n",
    "import time\n",
    "# 检查GPU是否可用\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"使用设备: {device}\")\n",
    "if torch.cuda.is_available():\n",
    "print(f\"GPU型号: {torch.cuda.get_device_name(0)}\")\n",
    "# 数据加载和预处理\n",
    "def load_and_preprocess_data(file_path):\n",
    "#\"\"\"加载和预处理文本数据\"\"\"\n",
    "sentences = []\n",
    "with open(file_path, 'r', encoding='utf-8') as f:\n",
    "for line in f:\n",
    "# 提取文本内容（去掉标签数字）\n",
    "content = re.sub(r'^\\d+\\s*', '', line.strip())\n",
    "if len(content) > 5: # 只处理长度大于5的文本\n",
    "sentences.append(content)\n",
    "return sentences\n",
    "# 加载数据\n",
    "file_path = \"./train.txt\"\n",
    "sentences = load_and_preprocess_data(file_path)\n",
    "print(f\"总共加载了 {len(sentences)} 条文本数据\")\n",
    "print(\"前5条数据示例：\")\n",
    "for i in range(min(5, len(sentences))):\n",
    "print(f\"{i+1}: {sentences[i][:50]}...\")\n",
    "# 中文分词处理\n",
    "def chinese_tokenize(sentences):\n",
    "#\"\"\"对中文文本进行分词处理\"\"\"\n",
    "tokenized_sentences = []\n",
    "for i, sentence in enumerate(sentences):\n",
    "# 使用jieba进行分词\n",
    "words = jieba.lcut(sentence)\n",
    "# 过滤掉空格和短词\n",
    "words = [word.strip() for word in words if len(word.strip()) > 1]\n",
    "tokenized_sentences.append(words)\n",
    "if i % 200 == 0: # 每200条显示进度\n",
    "print(f\"已处理 {i}/{len(sentences)} 条数据\")\n",
    "return tokenized_sentences\n",
    "tokenized_corpus = chinese_tokenize(sentences)\n",
    "print(\"分词完成！\")\n",
    "print(\"\\n分词后的数据示例：\")\n",
    "for i in range(min(3, len(tokenized_corpus))):\n",
    "print(f\"原文: {sentences[i][:30]}...\")\n",
    "print(f\"分词: {tokenized_corpus[i][:10]}...\")\n",
    "# 词汇统计分析\n",
    "def analyze_vocabulary(tokenized_corpus):\n",
    "\"\"\"分析词汇统计信息\"\"\"\n",
    "all_words = [word for sentence in tokenized_corpus for word in sentence]\n",
    "word_freq = Counter(all_words)\n",
    "print(\"词汇统计信息：\")\n",
    "print(f\"总词汇量: {len(all_words)}\")\n",
    "print(f\"唯一词汇数: {len(word_freq)}\")\n",
    "print(f\"平均句子长度: {np.mean([len(sentence) for sentence in tokenized_corpus]):.2f}\")\n",
    "print(f\"最长句子长度: {max([len(sentence) for sentence in tokenized_corpus])}\")\n",
    "print(f\"最短句子长度: {min([len(sentence) for sentence in tokenized_corpus])}\")\n",
    "# 显示最高频词汇\n",
    "print(\"\\n前20个最高频词汇：\")\n",
    "for word, freq in word_freq.most_common(20):\n",
    "print(f\"{word}: {freq}次\")\n",
    "return word_freq\n",
    "word_frequency = analyze_vocabulary(tokenized_corpus)\n",
    "# 构建词汇表\n",
    "def build_vocab(tokenized_corpus, min_count=5):\n",
    "#\"\"\"构建词汇表和索引映射\"\"\"\n",
    "# 统计词频\n",
    "word_counts = Counter([word for sentence in tokenized_corpus for word in sentence])\n",
    "# 过滤低频词\n",
    "vocab = {word: count for word, count in word_counts.items() if count >= min_count}\n",
    "# 创建索引映射\n",
    "idx_to_word = ['<PAD>', '<UNK>'] + list(vocab.keys())\n",
    "word_to_idx = {word: idx for idx, word in enumerate(idx_to_word)}\n",
    "print(f\"词汇表大小: {len(word_to_idx)} (包含 {len(word_counts) - len(vocab)} 个低频词被过\n",
    "滤)\")\n",
    "return word_to_idx, idx_to_word, vocab\n",
    "word_to_idx, idx_to_word, vocab = build_vocab(tokenized_corpus, min_count=5)\n",
    "# 创建训练数据（负采样）\n",
    "def create_training_data(tokenized_corpus, word_to_idx, window_size=5, num_negatives=5):\n",
    "\"\"\"创建Word2Vec训练数据（Skip-gram with Negative Sampling）\"\"\"\n",
    "training_data = []\n",
    "vocab_size = len(word_to_idx)\n",
    "unk_idx = word_to_idx.get('<UNK>', 0)\n",
    "# 计算词频分布用于负采样\n",
    "word_counts = np.zeros(vocab_size)\n",
    "for word, idx in word_to_idx.items():\n",
    "if word in vocab:\n",
    "word_counts[idx] = vocab[word]\n",
    "# 负采样分布（按词频的3/4次方）\n",
    "word_distribution = np.power(word_counts, 0.75)\n",
    "word_distribution = word_distribution / word_distribution.sum()\n",
    "for sentence in tokenized_corpus:\n",
    "# 转换为索引\n",
    "sentence_indices = [word_to_idx.get(word, unk_idx) for word in sentence]\n",
    "for i, target_word_idx in enumerate(sentence_indices):\n",
    "# 获取上下文窗口\n",
    "start = max(0, i - window_size)\n",
    "end = min(len(sentence_indices), i + window_size + 1)\n",
    "for j in range(start, end):\n",
    "if j != i: # 跳过目标词本身\n",
    "context_word_idx = sentence_indices[j]\n",
    "training_data.append((target_word_idx, context_word_idx))\n",
    "print(f\"创建了 {len(training_data)} 个训练样本\")\n",
    "return training_data, word_distribution\n",
    "# 创建训练数据\n",
    "training_data, word_distribution = create_training_data(\n",
    "tokenized_corpus, word_to_idx, window_size=5, num_negatives=5\n",
    ")\n",
    "# 自定义Dataset\n",
    "class Word2VecDataset(Dataset):\n",
    "def __init__(self, training_data, word_distribution, num_negatives=5):\n",
    "self.training_data = training_data\n",
    "self.word_distribution = word_distribution\n",
    "self.num_negatives = num_negatives\n",
    "self.vocab_size = len(word_distribution)\n",
    "def __len__(self):\n",
    "return len(self.training_data)\n",
    "def __getitem__(self, idx):\n",
    "target, context = self.training_data[idx]\n",
    "# 负采样\n",
    "negative_samples = []\n",
    "while len(negative_samples) < self.num_negatives:\n",
    "# 从分布中采样负样本\n",
    "negative = np.random.choice(self.vocab_size, p=self.word_distribution)\n",
    "if negative != target and negative != context:\n",
    "negative_samples.append(negative)\n",
    "return {\n",
    "'target': torch.tensor(target, dtype=torch.long),\n",
    "'context': torch.tensor(context, dtype=torch.long),\n",
    "'negatives': torch.tensor(negative_samples, dtype=torch.long)\n",
    "}\n",
    "# Word2Vec模型（Skip-gram with Negative Sampling）\n",
    "class Word2VecModel(nn.Module):\n",
    "def __init__(self, vocab_size, embedding_dim=50):\n",
    "super(Word2VecModel, self).__init__()\n",
    "self.target_embeddings = nn.Embedding(vocab_size, embedding_dim)\n",
    "self.context_embeddings = nn.Embedding(vocab_size, embedding_dim)\n",
    "# 初始化权重\n",
    "init_range = 0.5 / embedding_dim\n",
    "self.target_embeddings.weight.data.uniform_(-init_range, init_range)\n",
    "self.context_embeddings.weight.data.uniform_(-init_range, init_range)\n",
    "def forward(self, target_word, context_word, negative_words):\n",
    "# 获取词向量\n",
    "target_embed = self.target_embeddings(target_word) # [batch_size, embedding_dim]\n",
    "context_embed = self.context_embeddings(context_word) # [batch_size, embedding_dim]\n",
    "negative_embed = self.context_embeddings(negative_words) # [batch_size,\n",
    "num_negatives, embedding_dim]\n",
    "# 计算正样本得分\n",
    "positive_score = torch.sum(target_embed * context_embed, dim=1) # [batch_size]\n",
    "positive_score = torch.clamp(positive_score, max=10, min=-10)\n",
    "# 计算负样本得分\n",
    "target_embed_expanded = target_embed.unsqueeze(1) # [batch_size, 1, embedding_dim]\n",
    "negative_score = torch.bmm(negative_embed, target_embed_expanded.transpose(1, 2)) #\n",
    "[batch_size, num_negatives, 1]\n",
    "negative_score = torch.clamp(negative_score.squeeze(2), max=10, min=-10) #\n",
    "[batch_size, num_negatives]\n",
    "return positive_score, negative_score\n",
    "# 损失函数\n",
    "def skipgram_loss(positive_score, negative_score):\n",
    "\"\"\"Skip-gram with Negative Sampling损失函数\"\"\"\n",
    "# 正样本损失\n",
    "positive_loss = -torch.log(torch.sigmoid(positive_score))\n",
    "# 负样本损失\n",
    "negative_loss = -torch.sum(torch.log(torch.sigmoid(-negative_score)), dim=1)\n",
    "return (positive_loss + negative_loss).mean()\n",
    "# 训练函数\n",
    "def train_word2vec_gpu(model, dataset, batch_size=1024, epochs=1, learning_rate=0.025):\n",
    "\"\"\"在GPU上训练Word2Vec模型\"\"\"\n",
    "model = model.to(device)\n",
    "# 创建DataLoader\n",
    "dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=0)\n",
    "# 优化器\n",
    "optimizer = optim.Adam(model.parameters(), lr=learning_rate)\n",
    "# 学习率调度器\n",
    "scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)\n",
    "print(f\"\\n开始训练...\")\n",
    "print(f\"批量大小: {batch_size}\")\n",
    "print(f\"训练轮数: {epochs}\")\n",
    "print(f\"优化器: Adam, 学习率: {learning_rate}\")\n",
    "losses = []\n",
    "for epoch in range(epochs):\n",
    "model.train()\n",
    "total_loss = 0\n",
    "start_time = time.time()\n",
    "for batch_idx, batch in enumerate(dataloader):\n",
    "# 将数据移到GPU\n",
    "target_words = batch['target'].to(device)\n",
    "context_words = batch['context'].to(device)\n",
    "negative_words = batch['negatives'].to(device)\n",
    "# 前向传播\n",
    "optimizer.zero_grad()\n",
    "positive_score, negative_score = model(target_words, context_words,\n",
    "negative_words)\n",
    "# 计算损失\n",
    "loss = skipgram_loss(positive_score, negative_score)\n",
    "# 反向传播\n",
    "loss.backward()\n",
    "optimizer.step()\n",
    "total_loss += loss.item()\n",
    "if batch_idx % 100 == 0:\n",
    "print(f\"Epoch {epoch+1}/{epochs} | Batch {batch_idx}/{len(dataloader)} |\n",
    "Loss: {loss.item():.4f}\")\n",
    "# 更新学习率\n",
    "scheduler.step()\n",
    "avg_loss = total_loss / len(dataloader)\n",
    "losses.append(avg_loss)\n",
    "epoch_time = time.time() - start_time\n",
    "print(f\"Epoch {epoch+1}/{epochs} 完成 | 平均损失: {avg_loss:.4f} | 时间:\n",
    "{epoch_time:.2f}秒\")\n",
    "# 每10轮保存一次中间结果\n",
    "if (epoch + 1) % 10 == 0:\n",
    "print(f\"保存第 {epoch+1} 轮的词向量...\")\n",
    "print(\"\\n训练完成！\")\n",
    "return model, losses\n",
    "# 创建数据集和模型\n",
    "dataset = Word2VecDataset(training_data, word_distribution, num_negatives=5)\n",
    "model = Word2VecModel(vocab_size=len(word_to_idx), embedding_dim=50)\n",
    "# 训练模型\n",
    "trained_model, losses = train_word2vec_gpu(\n",
    "model, dataset, batch_size=1024, epochs=1, learning_rate=0.025\n",
    ")\n",
    "# 提取词向量\n",
    "def get_word_vectors(model, word_to_idx):\n",
    "\"\"\"从训练好的模型中提取词向量并保存为 .pt 文件\"\"\"\n",
    "model.eval()\n",
    "with torch.no_grad():\n",
    "# 获取目标词向量\n",
    "all_indices = torch.arange(len(word_to_idx)).to(device)\n",
    "word_vectors = model.target_embeddings(all_indices).detach().cpu() # 保留为 PyTorch\n",
    "张量\n",
    "# 创建词向量字典（键为词，值为张量）\n",
    "word_vectors_dict = {}\n",
    "for word, idx in word_to_idx.items():\n",
    "word_vectors_dict[word] = word_vectors[idx]\n",
    "return word_vectors_dict, word_vectors\n",
    "word_vectors_dict, all_vectors = get_word_vectors(trained_model, word_to_idx)\n",
    "# 保存词向量为 .pt 文件\n",
    "def save_word_vectors_pt(word_vectors_dict, output_path):\n",
    "\"\"\"将词向量字典保存为 .pt 文件\"\"\"\n",
    "torch.save(word_vectors_dict, output_path)\n",
    "print(f\"词向量已保存到: {output_path}\")\n",
    "# 加载词向量从 .pt 文件\n",
    "def load_word_vectors_pt(input_path):\n",
    "\"\"\"从 .pt 文件加载词向量字典\"\"\"\n",
    "word_vectors_dict = torch.load(input_path)\n",
    "print(f\"词向量已从 {input_path} 加载\")\n",
    "return word_vectors_dict\n",
    "# 保存词向量\n",
    "save_word_vectors_pt(word_vectors_dict, \"word_vectors.pt\")\n",
    "# 加载词向量\n",
    "loaded_word_vectors_dict = load_word_vectors_pt(\"word_vectors.pt\")\n",
    "# 创建与gensim兼容的Word2Vec接口\n",
    "class PyTorchWord2VecWrapper:\n",
    "def __init__(self, word_vectors_dict, word_to_idx, idx_to_word):\n",
    "self.wv = self.WordVectors(word_vectors_dict, word_to_idx, idx_to_word)\n",
    "self.vector_size = list(word_vectors_dict.values())[0].shape[0]\n",
    "class WordVectors:\n",
    "def __init__(self, word_vectors_dict, word_to_idx, idx_to_word):\n",
    "self.vectors_dict = word_vectors_dict\n",
    "self.word_to_idx = word_to_idx\n",
    "self.idx_to_word = idx_to_word\n",
    "self.key_to_index = word_to_idx\n",
    "self.vectors = np.stack(list(word_vectors_dict.values()))\n",
    "def __getitem__(self, word):\n",
    "return self.vectors_dict.get(word, None)\n",
    "def __contains__(self, word):\n",
    "return word in self.vectors_dict\n",
    "def similarity(self, word1, word2):\n",
    "\"\"\"计算两个词的余弦相似度\"\"\"\n",
    "if word1 not in self.vectors_dict or word2 not in self.vectors_dict:\n",
    "raise KeyError(f\"词语不在词汇表中: {word1} 或 {word2}\")\n",
    "vec1 = self.vectors_dict[word1]\n",
    "vec2 = self.vectors_dict[word2]\n",
    "# 计算余弦相似度\n",
    "norm1 = np.linalg.norm(vec1)\n",
    "norm2 = np.linalg.norm(vec2)\n",
    "if norm1 == 0 or norm2 == 0:\n",
    "return 0.0\n",
    "similarity = np.dot(vec1, vec2) / (norm1 * norm2)\n",
    "return similarity\n",
    "def most_similar(self, word, topn=10):\n",
    "\"\"\"查找与给定词最相似的词\"\"\"\n",
    "if word not in self.vectors_dict:\n",
    "raise KeyError(f\"词语不在词汇表中: {word}\")\n",
    "target_vec = self.vectors_dict[word]\n",
    "similarities = []\n",
    "for w, vec in self.vectors_dict.items():\n",
    "if w == word:\n",
    "continue\n",
    "norm_target = np.linalg.norm(target_vec)\n",
    "norm_vec = np.linalg.norm(vec)\n",
    "if norm_target == 0 or norm_vec == 0:\n",
    "sim = 0.0\n",
    "else:\n",
    "sim = np.dot(target_vec, vec) / (norm_target * norm_vec)\n",
    "similarities.append((w, sim))\n",
    "# 按相似度排序\n",
    "similarities.sort(key=lambda x: x[1], reverse=True)\n",
    "return similarities[:topn]\n",
    "# 创建包装器\n",
    "w2v_model = PyTorchWord2VecWrapper(loaded_word_vectors_dict, word_to_idx, idx_to_word)\n",
    "# 测试相似词查找功能\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"词向量模型测试\")\n",
    "print(\"=\"*50)\n",
    "test_words = ['中国', '美国', '基金', '房价']\n",
    "print(\"\\n相似词查找测试：\")\n",
    "for word in test_words:\n",
    "if word in w2v_model.wv:\n",
    "similar_words = w2v_model.wv.most_similar(word, topn=5)\n",
    "print(f\"\\n与'{word}'最相似的词：\")\n",
    "for similar, score in similar_words:\n",
    "print(f\" {similar}: {score:.3f}\")\n",
    "else:\n",
    "print(f\"'{word}'不在词汇表中\")\n",
    "# 词汇相似度计算\n",
    "print(\"\\n词汇相似度计算：\")\n",
    "word_pairs = [('中国', '美国'), ('基金', '股票'), ('房价', '楼市'), ('北京', '上海')]\n",
    "for word1, word2 in word_pairs:\n",
    "if word1 in w2v_model.wv and word2 in w2v_model.wv:\n",
    "similarity = w2v_model.wv.similarity(word1, word2)\n",
    "print(f\"'{word1}' 和 '{word2}' 的相似度: {similarity:.3f}\")\n",
    "else:\n",
    "print(f\"词汇对 ({word1}, {word2}) 中有词不在词汇表中\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
